### ISSUE TITLE
Net Error Connection Refused in Console

### ISSUE THREAD

**Issue by fredguth** [neighbourhoodie/svelte-pouchdb-couchdb#2]
I just cloned and npm installed the repo.  When `npm run dev` error appears in console. I am not sure if it is really an error, or is a "pouchdb thing".

**Comment by ghost** [comment]
what error exactly? does it still happens?

**Comment by fredguth** [comment]
I am closing, because I tried again and now it works.  Sorry.

**Comment by ghost** [comment]
only took ~~a year~~ 2 years :laughing:

**Comment by fredguth** [comment]
😆 2 years... sorry.
